Add minimum_data_rate_2g and minimum_data_rate_5g fields to unifi_wlan
paultyng/terraform-provider-unifi pull request #159
Opened 2021-07-20 03:53 UTC by kurtmc

2021-07-20 06:24 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +				ValidateFunc: validation.StringInSlice([]string{"1Mbps", "2Mbps", "5.5Mbps", "6Mbps", "9Mbps", "11Mbps", "12Mbps", "18Mbps", "24Mbps", "36Mbps", "48Mbps", "54Mbps"}, false),
I think it would be better to rely on server side validation. I am not sure but the accepted values could depend on firmware or controller version.

2021-07-20 06:24 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +				Type:         schema.TypeString,
I think it would be more user friendly to make these fields integers instead of strings. @paultyng what do you think?

2021-07-22 23:20 UTC, kurtmc commented
I have converted this PR to a draft, as my intention is to get some feedback around what the best way to add this functionality to this resource would be.

The way this PR has implemented it, is to add single fields, looking like this:
```terraform
resource "unifi_wlan" "test" {
  name          = "tfacc-wpapsk"
  network_id    = unifi_network.test.id
  passphrase    = "12345678"
  ap_group_ids  = [data.unifi_ap_group.default.id]
  user_group_id = data.unifi_user_group.default.id
  security      = "wpapsk"

  minimum_data_rate_2g = "5.5Mbps"
  minimum_data_rate_5g = "18Mbps"
}
```

but since in the UI it comes under a drop down, we could represent it with a block?
```terraform
resource "unifi_wlan" "test" {
  name          = "tfacc-wpapsk"
  network_id    = unifi_network.test.id
  passphrase    = "12345678"
  ap_group_ids  = [data.unifi_ap_group.default.id]
  user_group_id = data.unifi_user_group.default.id
  security      = "wpapsk"

  rate_and_beacon_controls {
    minimum_data_rate_2g = "5.5Mbps"
    minimum_data_rate_5g = "18Mbps"
  }
}
```

2021-08-01 06:07 UTC, joshuaspence commented
Sorry for the delay, have been a bit busy lately.

Regarding whether or not this should be a block or not, I'm thinking it shouldn't. Maybe there's other use cases but I think the main reason you would use a block is to group related attributes and simplify validation. For example, if all or none of the attributes must be set then this would be easier to validate using a nested schema.

2021-08-01 06:29 UTC, joshuaspence requested changes
Poking around the UI and I think that these should be nested schemas as there are multiple related options:

![UniFi-Network](https://user-images.githubusercontent.com/234676/127761549-21633116-64ea-4550-93fc-ee5fb119bd0f.png)

We don't need to support all of these options now but I think we would want to eventually. So to prepare for that, I think it should look like this:

```
minimium_data_rate_control_2g {
  rate = "54Mbps"
}

minimium_data_rate_control_5g {
  rate = "54Mbps"
}
```

Another option which might cut down on some duplication:

```
minimium_data_rate_control {
  type = "5g"
  rate = "54Mbps"
}
```

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +				Description:  "Enable minimum data rate control for 2G devices",
A minor point but I would drop the word "enable" here as, to me at least, it seems to suggest that this is on or off.

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +				ValidateFunc: validation.StringInSlice([]string{"1Mbps", "2Mbps", "5.5Mbps", "6Mbps", "9Mbps", "11Mbps", "12Mbps", "18Mbps", "24Mbps", "36Mbps", "48Mbps", "54Mbps"}, false),
I still think `schema.TypeFloat` would be better here but I could be convinced either way.

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +			d.Set("minimum_data_rate_2g", fmt.Sprintf("%dMbps", resp.MinrateNgDataRateKbps/1000))
If the API is passing this as a float then I think that further supports the use of `schema.TypeFloat` for these attributes

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +	if resp.MinrateNgEnabled {
I think the way this code is written means that if data rate controls are disabled then the old value will persist in the state?

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan_test.go
> +data "unifi_ap_group" "default" {
A minor point but I'd prefer that the Terraform code is formatted as per `terraform fmt`

2021-08-01 06:29 UTC, joshuaspence commented on internal/provider/resource_wlan_test.go
> +data "unifi_ap_group" "default" {
A minor point but I'd prefer that the Terraform code is formatted as per `terraform fmt`

2021-08-10 14:56 UTC, paultyng commented
This PR looks good to me, aside from the minor comments by @joshuaspence. Just some additional context on a couple of the items:

* **Flat vs nested schema**: there has historically been some complications in TF core with diffing and optional/computed things as schema gets nested, I think in terms of ease of implementation and compatibility flatter is generally better.
* **Numbers vs strings**: this one really just boils down to what the API expects. Generally I prefer to model the API as closely and granularly as possible and then let folks build on top of that with nicer enhancements via modules, etc. So if the API takes bandwidth in string form with the unit suffix, I would have the provider take it that way, if it takes an int, same in provider, etc.

2021-08-11 03:10 UTC, joshuaspence commented
@paultyng Thanks for sharing your thoughts, makes sense to me :+1:

2021-09-10 22:41 UTC, kurtmc commented
@paultyng sorry I abandoned this, it just dropped off my priority list. Thank you so much for finishing this for me! Looks good to me, the switch to using integers makes a lot of sense!

2021-09-11 02:16 UTC, merged