Add `golangci-lint`
paultyng/terraform-provider-unifi pull request #192
Opened 2021-09-22 12:08 UTC by joshuaspence

2021-09-23 14:29 UTC, paultyng commented on .github/workflows/ci.yaml
> +  build:
Should we remove this one from acctest?

2021-09-23 14:29 UTC, paultyng approved these changes

2021-09-24 12:27 UTC, paultyng commented on .github/workflows/acctest.yml
>      needs: build
Need to remove this as well I think.

2021-09-24 12:27 UTC, paultyng requested changes
Need to remove the dependency in acctest, see comment inline

2021-09-25 02:14 UTC, joshuaspence commented
Ah, I saw that the checks all passed but didn't see that `acctest` was now invalid.

2021-09-26 13:56 UTC, merged