Add wlan tuning
paultyng/terraform-provider-unifi pull request #312
Opened 2023-02-26 20:38 UTC by virtualguy

* proxy_arp
* bss_transition
* fast_roaming_enabled

2023-02-28 13:49 UTC, joshuaspence requested changes

2023-02-28 13:49 UTC, joshuaspence commented on docs/resources/wlan.md
> +- `bss_transition` (Boolean) Enable BSS Transition Defaults to `false`.
Add a period to the description

2023-02-28 13:49 UTC, joshuaspence commented on docs/resources/wlan.md
> +- `fast_roaming_enabled` (Boolean) Enable Fast Roaming Defaults to `false`.
Also here

2023-02-28 13:49 UTC, joshuaspence commented on docs/resources/wlan.md
> +- `proxy_arp` (Boolean) Enable Proxy ARP Defaults to `false`.
And here

2023-02-28 13:49 UTC, joshuaspence commented on go.mod
> +module github.com/virtualguy/terraform-provider-unifi
Unrelated?

2023-02-28 13:49 UTC, joshuaspence commented on internal/provider/resource_wlan.go
> +				Default:     false,
This should default to true to match the UI

2023-02-28 13:49 UTC, joshuaspence commented on internal/provider/resource_wlan_test.go
> +				// testCheckNetworkExists(t, "name"),
You're not actually checking anything here

2023-03-10 03:14 UTC, joshuaspence approved these changes

2023-03-10 03:15 UTC, merged

2023-03-13 03:04 UTC, virtualguy commented
Thanks for the clean up @joshuaspence much appreciated

2023-03-13 06:58 UTC, joshuaspence commented
> Thanks for the clean up @joshuaspence much appreciated

No problem, I wanted to use these changes myself! Thanks for the contribution